/*
 * Copyright (c) 2026 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://edgeimpulse.com/legal/terms-of-service) or Enterprise Terms of
 * Service (https://edgeimpulse.com/legal/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */
// Generated on: 08.06.2026 08:14:09

#include <stdio.h>
#include <stdlib.h>
#include "edge-impulse-sdk/tensorflow/lite/c/builtin_op_data.h"
#include "edge-impulse-sdk/tensorflow/lite/c/common.h"
#include "edge-impulse-sdk/tensorflow/lite/micro/micro_mutable_op_resolver.h"
#include "edge-impulse-sdk/porting/ei_classifier_porting.h"

#if EI_CLASSIFIER_PRINT_STATE
#if defined(__cplusplus) && EI_C_LINKAGE == 1
extern "C" {
    extern void ei_printf(const char *format, ...);
}
#else
extern void ei_printf(const char *format, ...);
#endif
#endif

#define STRINGIZE(x) #x
#define STRINGIZE_VALUE_OF(x) STRINGIZE(x)

#if defined (__GNUC__)  /* GNU compiler */
#define ALIGN(X) __attribute__((aligned(X)))
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (_MSC_VER)
#define ALIGN(X) __declspec(align(X))
#elif defined (__TASKING__) /* TASKING Compiler */
#define ALIGN(X) __align(X)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__ARMCC_VERSION) /* Arm Compiler */
#define ALIGN(X) __ALIGNED(x)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__ICCARM__) /* IAR Compiler */
#define ALIGN(x) __attribute__((aligned(x)))
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__clang__) /* LLVM/Clang Compiler */
#define ALIGN(X) __ALIGNED(x)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#endif

#if defined(EI_MODEL_SECTION) && (defined(__GNUC__) || defined(__clang__))
#define MODEL_SECTION(X) __attribute__((section(STRINGIZE_VALUE_OF(X))))
#else
#define MODEL_SECTION(X)
#endif

#ifndef EI_MAX_SCRATCH_BUFFER_COUNT
#ifndef CONFIG_IDF_TARGET_ESP32S3
#define EI_MAX_SCRATCH_BUFFER_COUNT 4
#else
#define EI_MAX_SCRATCH_BUFFER_COUNT 4
#endif // CONFIG_IDF_TARGET_ESP32S3
#endif // EI_MAX_SCRATCH_BUFFER_COUNT

#ifndef EI_MAX_OVERFLOW_BUFFER_COUNT
#define EI_MAX_OVERFLOW_BUFFER_COUNT 10
#endif // EI_MAX_OVERFLOW_BUFFER_COUNT

using namespace tflite;
using namespace tflite::ops;
using namespace tflite::ops::micro;

namespace {

#if defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX) || defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX_GNU)
constexpr int kTensorArenaSize = 1552;
#else
constexpr int kTensorArenaSize = 528;
#endif

#if defined(EI_CLASSIFIER_ALLOCATION_STATIC)
#if defined (EI_TENSOR_ARENA_LOCATION)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16) DEFINE_SECTION(STRINGIZE_VALUE_OF(EI_TENSOR_ARENA_LOCATION));
#else
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#endif
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX)
#pragma Bss(".tensor_arena")
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#pragma Bss()
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX_GNU)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16) __attribute__((section(".tensor_arena")));
#else
#define EI_CLASSIFIER_ALLOCATION_HEAP 1
uint8_t* tensor_arena = NULL;
#endif

static uint8_t* tensor_boundary;
static uint8_t* current_location;

template <int SZ, class T> struct TfArray {
  int sz; T elem[SZ];
};

enum used_operators_e {
  OP_FULLY_CONNECTED, OP_SOFTMAX,  OP_LAST
};

struct TensorInfo_t { // subset of TfLiteTensor used for initialization from constant memory
  TfLiteAllocationType allocation_type;
  TfLiteType type;
  void* data;
  TfLiteIntArray* dims;
  size_t bytes;
  TfLiteQuantization quantization;
};

typedef struct {
  TfLiteTensor tensor;
  int16_t index;
} TfLiteTensorWithIndex;

typedef struct {
  TfLiteEvalTensor tensor;
  int16_t index;
} TfLiteEvalTensorWithIndex;

TfLiteContext ctx{};
static const int MAX_TFL_TENSOR_COUNT = 4;
static TfLiteTensorWithIndex tflTensors[MAX_TFL_TENSOR_COUNT];
static const int MAX_TFL_EVAL_COUNT = 4;
static TfLiteEvalTensorWithIndex tflEvalTensors[MAX_TFL_EVAL_COUNT];
TfLiteRegistration registrations[OP_LAST];

namespace g0 {
const TfArray<2, int> tensor_dimension0 = { 2, { 1,26 } };
const TfArray<1, float> quant0_scale = { 1, { 0.061152372509241104, } };
const TfArray<1, int> quant0_zero = { 1, { -76 } };
const TfLiteAffineQuantization quant0 = { (TfLiteFloatArray*)&quant0_scale, (TfLiteIntArray*)&quant0_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data1[4] = { -280, 285, 303, -314, };
const TfArray<1, int> tensor_dimension1 = { 1, { 4 } };
const TfArray<1, float> quant1_scale = { 1, { 0.00024979369482025504, } };
const TfArray<1, int> quant1_zero = { 1, { 0 } };
const TfLiteAffineQuantization quant1 = { (TfLiteFloatArray*)&quant1_scale, (TfLiteIntArray*)&quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data2[4*16] = { 
  -25, 77, 72, -127, -98, 122, 97, -29, 80, 15, 40, 2, -68, 91, 59, 70, 
  -120, 38, -73, 75, -35, -30, -102, -67, -55, -112, 64, 105, -49, -63, 62, 9, 
  -79, -74, -49, -66, -106, -4, -39, 28, -35, 89, 82, -55, -41, 104, -84, -112, 
  -13, -54, 25, 33, -63, 64, 48, 114, -84, -106, -68, -69, -94, 14, 37, -54, 
};
const TfArray<2, int> tensor_dimension2 = { 2, { 4,16 } };
const TfArray<1, float> quant2_scale = { 1, { 0.0049957972951233387, } };
const TfLiteAffineQuantization quant2 = { (TfLiteFloatArray*)&quant2_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data3[16] = { -179, -154, -59, 317, -194, 197, -240, -284, -138, 364, 395, 449, 293, -61, 0, -165, };
const TfArray<1, int> tensor_dimension3 = { 1, { 16 } };
const TfArray<1, float> quant3_scale = { 1, { 0.00020907884754706174, } };
const TfLiteAffineQuantization quant3 = { (TfLiteFloatArray*)&quant3_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data4[16*16] = { 
  -37, 73, 2, -33, -72, -93, 32, 70, 73, -4, -38, -59, 100, 111, -101, -29, 
  -57, -39, 12, 62, -94, -6, -97, 91, 2, 7, -101, 37, 3, 14, 88, -39, 
  -47, -127, 23, 78, 47, -83, 93, -53, -30, 95, 14, 4, -66, 5, -9, 22, 
  -92, -52, 74, 9, 34, 123, -100, -100, 68, 64, 85, 32, -75, 97, 3, 57, 
  -68, 45, 52, -75, 19, 50, 75, -94, 16, -48, -83, -73, 25, 67, 28, 15, 
  -85, -49, 42, 102, -9, -45, 105, 2, 10, -13, -21, 56, -77, 56, -52, -29, 
  -45, 26, -44, 112, -87, -8, 5, 0, -7, 103, 20, -77, -14, 18, 61, 52, 
  -75, 58, 99, -28, 95, -73, -2, -8, 84, -54, 17, -30, 19, 20, 54, -68, 
  -93, 64, 96, -84, -86, -51, 42, -103, 88, -19, -52, -5, 56, -81, 5, 17, 
  -57, -26, -4, -15, 97, 9, 109, 83, -8, 110, -24, 12, 94, -75, -19, 35, 
  76, 71, -2, -106, 22, -55, -50, 105, -38, -30, 100, 75, 61, 73, 2, -78, 
  65, -2, 35, -2, -56, 13, 103, -15, -72, -10, 87, 28, -19, 2, -61, -48, 
  67, 109, 74, -72, 74, 80, 121, 17, 78, -62, 58, -29, -76, -79, -53, 14, 
  -31, -62, 14, -34, -52, 34, -98, -100, 7, 13, -23, 35, -56, -84, -40, 39, 
  -85, -61, 51, 63, -17, -62, -41, -78, -22, 17, -72, -94, 11, -92, -24, 4, 
  -26, -24, 6, 79, 9, 39, -73, 32, -79, 25, 84, -43, -18, -18, -63, -61, 
};
const TfArray<2, int> tensor_dimension4 = { 2, { 16,16 } };
const TfArray<1, float> quant4_scale = { 1, { 0.0043423781171441078, } };
const TfLiteAffineQuantization quant4 = { (TfLiteFloatArray*)&quant4_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data5[16] = { -148, 212, 1287, 549, 435, 838, 623, 249, 214, 429, 918, -90, -166, 487, -207, -28, };
const TfArray<1, float> quant5_scale = { 1, { 0.00010853185085579753, } };
const TfLiteAffineQuantization quant5 = { (TfLiteFloatArray*)&quant5_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data6[16*32] = { 
  57, 3, 79, -46, -18, 23, -3, -71, -7, 36, 16, 71, 16, 13, -82, -24, 34, -85, -6, -58, -81, 24, 16, 14, 56, -20, -79, -41, 16, 60, 77, -15, 
  57, -67, -10, 51, 49, -92, 82, 52, 35, 21, -41, -71, 81, -71, 73, -56, -103, 8, -48, 88, 18, -69, 96, -55, -44, -11, 23, -23, -17, -16, 27, 36, 
  -61, 80, 92, 8, 92, 116, -24, -55, -20, 5, 34, -58, 96, 9, 116, -10, 72, 75, -21, 20, 39, -43, -27, -42, 45, 26, 39, 14, 127, 6, 87, 42, 
  19, 46, -57, -72, -3, 66, 11, -51, 92, 9, -53, 72, 27, 62, 23, -66, 11, -5, -23, -82, -43, 108, 61, -63, -59, -12, 43, 123, 19, -12, -38, 55, 
  72, -73, 28, 79, 58, -95, 57, 79, 57, 13, -52, 7, 80, -34, -35, -4, -65, 50, 4, 18, 39, -13, 114, -65, 81, 77, -1, 36, 65, 84, 49, 5, 
  -3, -39, 46, -27, 16, 25, -15, 92, -35, -71, 45, 34, 48, -66, 44, 28, -20, -21, -4, 69, -49, -79, 32, 54, -8, 7, 100, -103, -3, -77, 50, 18, 
  96, -46, -72, 26, -33, 34, -54, 36, 73, -75, -15, 34, 7, 28, 90, 52, 90, 41, 67, -49, -6, 13, 65, -93, -32, -65, 102, -11, -81, -67, -80, -70, 
  8, -30, -109, -39, -55, -68, -33, 74, -29, -12, 27, 50, 40, 39, 32, -42, -8, 72, 71, 7, 96, 65, 21, -15, -12, -33, 57, 73, -108, -76, -36, -28, 
  83, -87, 56, 2, -85, -58, 94, -63, -56, -12, 3, 45, 48, -79, 65, 99, -53, 98, -12, 34, -1, 98, 90, 6, 21, 93, -82, 109, -2, -13, 48, -6, 
  -44, 28, 58, 42, 30, 9, -23, 34, 49, -81, -47, -56, 97, -12, 83, -3, 103, 40, 56, -28, -29, -52, -5, -50, 80, -57, 3, 88, -36, 5, 93, -101, 
  -35, 110, 65, 45, -92, 69, -90, 29, 90, -19, 36, 9, 2, -60, 64, 3, 9, 61, 95, 94, -41, 68, 54, 98, -18, -41, 42, -5, -9, 67, 42, 72, 
  -2, 60, -16, 69, -73, 38, 61, -64, -42, -6, -86, -40, 4, 22, -72, -73, 72, -55, 37, -62, -43, -89, -52, -46, -37, -75, 46, 46, -75, -29, 15, 5, 
  -31, -21, -10, -77, -6, 6, 41, -33, -32, 0, -10, -67, -60, 41, -70, 74, -6, -32, -46, -52, 40, 25, 41, -72, 83, -68, -9, 49, 6, -35, -17, 31, 
  -84, 34, 37, 48, 85, -82, 93, -85, -39, 11, 63, -55, 94, -54, 84, 68, 100, -40, -62, -25, 36, 64, -48, -53, -61, 22, -55, 0, 107, -36, 71, -105, 
  -69, 36, 30, 61, 47, -14, 18, 43, 39, 48, 65, 3, 15, -75, -77, -77, -24, 16, -10, 13, 86, -46, 49, -83, 69, 61, 6, 44, -5, 77, -47, -11, 
  38, -25, 31, 85, 85, 21, -86, -75, -60, -66, -71, 6, 57, 9, -81, -29, -43, 34, 81, -88, 65, 13, -67, -74, -85, -64, -34, -16, -46, -42, 29, -82, 
};
const TfArray<2, int> tensor_dimension6 = { 2, { 16,32 } };
const TfArray<1, float> quant6_scale = { 1, { 0.0040006265044212341, } };
const TfLiteAffineQuantization quant6 = { (TfLiteFloatArray*)&quant6_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data7[32] = { -150, 422, 616, -364, -168, 606, 175, 685, 658, -87, 65, 508, 516, -235, 640, -90, 353, 547, 718, 403, 473, 497, 638, -68, -114, 153, 699, 1079, 499, -239, 122, 359, };
const TfArray<1, int> tensor_dimension7 = { 1, { 32 } };
const TfArray<1, float> quant7_scale = { 1, { 0.00013493755250237882, } };
const TfLiteAffineQuantization quant7 = { (TfLiteFloatArray*)&quant7_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data8[32*32] = { 
  11, 65, -49, 23, -10, -4, -59, 77, 12, 25, -80, 28, 11, 75, 48, -23, -7, -4, -40, 74, -19, 58, 90, 4, -68, -54, -22, 41, 79, -17, -70, -29, 
  -10, -5, 22, -37, -49, -29, 51, 45, 60, 15, -34, 23, 11, 54, -54, 97, -17, 88, -33, 38, 49, -16, -31, -65, -38, 70, 88, 13, -44, 19, 44, 28, 
  14, -16, 34, 11, 91, 59, 46, 11, -50, 41, -6, 83, 80, -41, -35, 93, -20, 22, 61, -37, -4, 93, 64, 0, 46, -33, -66, -48, -61, 95, 87, 59, 
  24, 40, 46, -65, 22, -28, -3, -51, -55, -40, 30, 33, 45, 21, -11, -70, -7, -84, -51, -10, -50, 75, -22, 55, 25, 45, 39, 36, -83, -38, -52, -26, 
  -34, -56, -74, 11, -69, -33, -30, 13, 28, 47, -62, -28, -62, -15, 31, 65, -20, -5, -68, -75, -33, 9, 68, 48, -38, -33, -13, 16, -37, -51, -15, -35, 
  -9, 34, 10, -13, -63, -26, 51, -34, -49, 39, 10, -16, -10, 31, 65, 8, -72, 42, 43, 82, 28, -13, -90, 20, 28, -45, -34, 13, 35, 6, 38, 16, 
  50, 44, -57, 32, 47, 38, -6, 28, -14, -30, -2, -65, -28, 56, -62, -60, 89, -73, 46, 10, 39, 72, 28, 75, 66, 30, -68, -32, 73, -41, 61, -34, 
  3, -14, -56, 89, 32, 64, 41, 63, 5, -46, 67, 77, -5, 12, 80, 63, -1, 39, -25, 67, -76, -14, -6, -49, -35, 18, 21, -16, -14, 32, 82, -46, 
  66, 72, 27, 52, -21, -39, 70, -75, -3, 67, 19, -1, 40, 97, 14, 74, -14, 24, 13, -13, -60, -48, 24, 70, 15, 87, 63, 48, 73, 65, 48, -23, 
  24, 33, -35, 50, -19, -16, 1, -19, -9, -32, -24, -34, -17, -54, -44, -18, -18, 60, 25, -40, -37, 52, -17, 21, -55, -28, 8, -43, 10, 9, -51, -67, 
  -42, -38, 40, 51, -62, -22, -45, -45, -46, -39, -24, -4, -12, -30, 18, 70, 54, 71, -26, 48, 18, -51, 14, -28, 46, -52, 21, 76, -77, 82, 36, -72, 
  -53, -44, 66, -17, -28, 34, 85, 12, -5, -41, -49, -36, 90, 55, 61, 48, -19, -57, -30, -17, 1, -33, -84, 39, -19, 61, 67, -51, 35, 46, -28, -63, 
  -81, -33, -26, 75, 57, -52, -46, -44, 57, 65, 46, -39, -49, -24, 45, 11, 71, -24, 37, 14, 20, 63, 37, 22, -5, -36, 15, -21, -23, 13, 27, 37, 
  6, -31, -76, -45, 38, -37, -76, -46, -36, 68, 48, -55, -12, -1, 45, 7, -33, -75, -65, 40, -39, 41, 28, 24, -14, -75, -56, -77, 8, 20, 44, -56, 
  69, 69, 0, 8, 6, 79, 8, 41, 73, 25, 25, 33, 86, 6, -49, 37, 82, 58, 63, 91, -37, -18, 19, -49, 11, 38, -4, -18, -33, -13, 101, 11, 
  36, 10, -2, -39, 11, 39, 22, 2, -33, 60, -61, 7, 46, 18, 4, -21, 0, 43, -37, 2, 66, 68, 59, -24, -27, -49, -60, 68, 2, 62, 30, -34, 
  58, 54, 4, 38, 14, -8, 13, -71, 35, 25, -39, 34, 43, 83, 5, -48, -11, 13, -5, -34, 53, 32, 60, -58, 54, 15, 67, 14, 58, -15, 10, -47, 
  55, 64, -73, 46, -7, 12, 82, 89, 20, -61, -40, -1, 42, -3, -40, -31, 93, 21, 47, -49, 26, -49, 78, 0, -21, -52, 74, -42, -21, -9, 62, -7, 
  50, -9, -17, 47, -9, 62, -73, 89, 31, -39, 5, 23, 52, 26, 51, 80, 76, -11, -17, -36, -88, -1, 0, -30, 39, 44, 65, -37, 86, 81, 24, 57, 
  -23, -27, 12, 46, -61, 62, -39, 29, 3, -29, -3, 60, -51, -14, -44, 13, -17, 0, 20, 67, 22, 55, -29, 76, 21, -79, -36, -5, -34, -1, -37, 62, 
  -67, -47, -72, 52, -31, -51, 36, 12, 42, -36, 60, 2, -50, 14, 70, -54, 101, -27, 88, 42, -33, 17, 0, 0, -18, 14, -54, -71, 23, 31, -14, 67, 
  62, 68, -84, 64, 54, -15, 74, -33, 91, 51, 23, 53, 80, 4, -2, -52, 29, 36, 55, 73, 78, 74, 54, 13, 31, 57, 77, -12, 22, 28, -53, -24, 
  14, 61, -14, 22, -39, -51, 10, 57, -57, 69, 28, -41, -2, -8, 48, -7, 12, -60, 67, 32, 86, -30, 31, 86, -20, -40, 50, -38, 1, -55, 49, 93, 
  85, -92, 105, 16, 51, 58, 41, 36, -10, -30, 25, 43, 51, -89, -30, 71, 22, 90, 44, 17, -28, 14, -70, 81, -59, -7, -61, 75, -61, 62, 17, 13, 
  -76, 44, -27, 62, -56, 39, -28, 98, -43, 32, 29, -20, -83, -10, -51, -43, 64, -10, 48, 26, -62, 2, 38, 22, -65, -54, 36, -25, -23, -26, -39, 33, 
  -59, 70, 34, 54, -19, -36, 48, 38, -37, 77, 40, 52, 83, -72, 56, 40, -36, -72, 14, -33, 42, 20, 56, -42, 63, -9, 1, 12, -2, 4, 20, 65, 
  -13, 7, -2, 5, -58, 6, -55, 47, 3, 48, 42, 97, 37, 80, 61, 81, -57, 3, -62, 86, 51, -5, 10, -12, 10, 50, -40, 22, 62, 4, 82, -15, 
  40, 104, -3, -22, -20, 41, -31, 31, 38, 92, -65, 5, 88, -12, -37, -67, 51, 12, 0, -15, -6, 32, 5, -60, -5, 127, 34, -22, 37, 14, 13, -2, 
  43, 96, 1, -14, 17, -21, 60, -19, 54, 39, -54, 44, -19, -48, 41, 35, 20, -4, -26, -25, 43, 14, -11, 69, -61, -73, 7, 14, -49, 38, 17, -45, 
  -17, -37, 42, -38, 32, -8, -69, -62, 12, -11, -60, 38, 0, -73, -48, -11, 6, -78, 69, 48, -75, -72, -10, 33, 36, 42, -1, -49, 12, -11, -27, -2, 
  8, -16, 53, -31, 67, 13, -1, -45, -73, 76, -65, -49, -26, -39, 79, -38, 67, 41, 11, 9, 55, -44, 30, 29, 49, -46, 71, -60, -41, -37, -40, -5, 
  74, -52, 6, 30, 12, -8, -47, 18, -67, -68, 20, 58, -42, -47, 68, 66, -73, 26, 51, 44, -19, -39, 20, -15, -4, -80, -73, 102, -14, 78, -40, 3, 
};
const TfArray<2, int> tensor_dimension8 = { 2, { 32,32 } };
const TfArray<1, float> quant8_scale = { 1, { 0.0040268413722515106, } };
const TfLiteAffineQuantization quant8 = { (TfLiteFloatArray*)&quant8_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data9[32] = { 521, 326, 199, 505, 63, -110, 323, 548, 278, 324, 1, 624, 427, 493, 334, 547, 526, 545, 345, 455, 297, 89, 417, 394, -66, 485, 473, -214, 431, 499, 651, -107, };
const TfArray<1, float> quant9_scale = { 1, { 0.00020371396385598928, } };
const TfLiteAffineQuantization quant9 = { (TfLiteFloatArray*)&quant9_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data10[32*26] = { 
  15, -100, -72, 109, 21, 56, 56, 29, 32, 34, 23, -34, -7, -63, 63, -111, -3, 91, -40, 77, 76, 95, -37, 34, -50, 59, 
  -113, -76, -22, 54, -103, 22, 2, -55, -52, -79, 55, -35, -8, 32, 7, 44, -109, -26, -26, -62, 63, -112, -106, 73, -29, -60, 
  94, -123, -43, 63, 72, 112, 54, 12, -56, 50, 21, -5, 73, -74, -71, 19, -50, -73, -60, -62, 58, 60, 62, 37, -56, 41, 
  -70, 98, 92, 8, 120, 64, 49, 107, 79, -21, -61, 56, 101, -18, 78, 44, 27, 52, 37, -17, 71, 42, -105, -104, 17, -94, 
  73, -71, -19, 41, -62, -54, -92, 49, -66, -41, 45, -49, 24, -39, -46, -41, -34, -11, -97, -54, 73, -67, -35, 62, -90, -3, 
  -20, 35, 18, 17, -79, -31, -7, -59, 26, -20, -80, 24, -64, -16, 12, 90, -75, 28, -68, 27, 65, 19, 21, -10, 72, 62, 
  24, -2, -111, -62, -55, -57, -57, 5, 25, -113, -56, -70, -3, -106, -51, -55, -93, -41, -94, 78, -13, -101, 76, -16, 67, -25, 
  96, 99, -1, 70, 3, -3, 94, 120, 87, 76, -5, -55, 22, 34, -111, -36, 31, 74, 48, -1, -10, -87, -53, -123, 1, -40, 
  40, -10, -50, -67, -28, -18, -17, -101, -57, -48, 29, -57, -44, 100, 30, 56, -43, -42, -69, 48, -3, -87, 65, -93, -45, -43, 
  -101, 96, -23, -85, -46, -71, -81, 6, 28, -84, -25, 78, -55, -92, -70, 77, -16, 83, 77, -27, -76, 52, 19, -58, 67, 6, 
  103, -83, 24, -86, -56, 5, -65, -80, 62, -50, 11, 3, -72, 26, -69, 75, 91, -79, 32, 54, -70, -22, -70, 43, -71, 43, 
  15, -73, -83, 63, 64, 101, 105, 60, 58, 13, -26, 34, 54, -51, 92, 37, -47, -14, 16, -40, 22, 67, 29, 41, 20, 57, 
  -64, 38, -26, 69, -51, -93, -48, -50, -55, 67, -8, -31, -52, 83, 19, 25, 93, 96, -78, 46, -74, -18, -38, 100, -48, -10, 
  3, 38, 40, 87, 59, -30, -110, 79, -48, -62, -124, -45, -57, 89, -26, -64, 57, 62, 67, 117, -42, 41, 120, 85, -28, 106, 
  84, -2, -65, -17, 101, 72, 19, -13, -60, 85, -62, 119, 50, 66, -101, -117, 124, 1, 63, 49, -51, -80, 57, -97, -87, -103, 
  41, -18, -44, -53, 125, 74, 17, 105, 125, 0, 21, -78, 17, -14, -22, 37, -4, -18, 65, 65, -18, -27, 42, 40, 78, 72, 
  -16, 90, 53, -89, -30, 38, 11, -77, 54, 64, -67, 108, 90, 34, -41, 28, 68, -66, -55, -95, 40, -109, -90, -97, 36, -26, 
  19, -126, -34, 126, 127, 63, -53, 37, 58, 22, -64, 61, -11, -80, -42, -40, 29, -3, 32, 15, 21, 70, -62, 9, 89, -81, 
  -99, 38, 30, -71, 53, -20, -89, -84, 77, -28, -8, 21, 82, 72, 64, -34, -57, -60, -49, -109, -81, 75, -99, 11, 87, -85, 
  6, 75, -5, 54, 67, 79, 88, 55, 52, -86, 5, 88, -51, 92, 6, -1, 84, 103, -29, 109, 100, 38, 105, -88, -22, -48, 
  -35, 22, -92, -40, -73, -99, -45, -83, 26, -57, 51, 60, -20, -76, 34, 45, -4, -99, 47, -112, -98, 39, -47, -95, -12, -28, 
  -24, -37, -39, -42, -13, 69, -2, -114, 52, 60, 29, -90, -77, -63, 83, 39, -71, -51, -76, -50, 72, -35, 48, -63, -3, -72, 
  -33, -21, -48, -6, 1, -24, 74, -14, -84, -63, 42, 55, -41, 60, 51, -49, -24, 67, -89, -100, -91, -36, -109, -90, 16, 28, 
  44, -84, 74, -38, -45, -91, -15, -44, -6, 40, -57, 29, 92, -108, -11, 36, -52, -101, 61, -35, -55, -22, -26, 7, 46, 47, 
  -4, -28, -85, 12, -109, 31, -108, 32, -43, 50, 44, 26, 78, 65, 62, -1, -31, 66, 7, 11, -77, -35, -87, -12, -61, 21, 
  64, 100, -91, 57, 116, 18, -47, -110, 39, -84, 7, 71, -30, 106, -23, -49, -22, 24, 10, -64, -28, 31, 94, 49, -11, 58, 
  -38, 71, -111, 82, 56, 5, -100, 14, -73, -51, -68, -68, -96, 77, 71, -34, 24, 96, -27, -28, 14, 115, -2, 72, -70, 39, 
  -64, -37, -58, 3, 28, 100, -54, 82, 70, 82, -31, -49, -25, -59, 65, 108, -60, 98, -19, -10, -71, 12, -50, 38, 77, 36, 
  66, 112, 50, 106, -43, -14, 21, 20, -87, 33, -40, -37, 49, 9, -58, 38, -16, 111, 51, 8, 20, 53, 85, 12, 7, -33, 
  73, -20, 79, 42, 113, -76, 57, 98, 32, -31, 61, -75, -91, -4, 110, 87, 93, 7, 5, -54, 9, -19, 50, 46, -68, 60, 
  37, -67, 18, -21, 0, 43, 26, -72, 51, -31, 1, 35, 84, -65, 57, -19, 78, 104, 57, -57, -50, -63, -112, -108, -56, -38, 
  54, 44, -60, 22, -16, 3, 101, -33, -37, -25, -14, 76, -93, -69, -70, 54, 50, -25, 19, -1, -60, -1, -19, 59, -29, 55, 
};
const TfArray<2, int> tensor_dimension10 = { 2, { 32,26 } };
const TfArray<1, float> quant10_scale = { 1, { 0.0033312519080936909, } };
const TfLiteAffineQuantization quant10 = { (TfLiteFloatArray*)&quant10_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const TfArray<2, int> tensor_dimension11 = { 2, { 1,32 } };
const TfArray<1, float> quant11_scale = { 1, { 0.033509526401758194, } };
const TfArray<1, int> quant11_zero = { 1, { -128 } };
const TfLiteAffineQuantization quant11 = { (TfLiteFloatArray*)&quant11_scale, (TfLiteIntArray*)&quant11_zero, 0 };
const TfArray<1, float> quant12_scale = { 1, { 0.027128713205456734, } };
const TfLiteAffineQuantization quant12 = { (TfLiteFloatArray*)&quant12_scale, (TfLiteIntArray*)&g0::quant11_zero, 0 };
const TfArray<2, int> tensor_dimension13 = { 2, { 1,16 } };
const TfArray<1, float> quant13_scale = { 1, { 0.048148468136787415, } };
const TfLiteAffineQuantization quant13 = { (TfLiteFloatArray*)&quant13_scale, (TfLiteIntArray*)&g0::quant11_zero, 0 };
const TfArray<1, float> quant14_scale = { 1, { 0.050000764429569244, } };
const TfLiteAffineQuantization quant14 = { (TfLiteFloatArray*)&quant14_scale, (TfLiteIntArray*)&g0::quant11_zero, 0 };
const TfArray<2, int> tensor_dimension15 = { 2, { 1,4 } };
const TfArray<1, float> quant15_scale = { 1, { 0.055426780134439468, } };
const TfArray<1, int> quant15_zero = { 1, { 15 } };
const TfLiteAffineQuantization quant15 = { (TfLiteFloatArray*)&quant15_scale, (TfLiteIntArray*)&quant15_zero, 0 };
const TfArray<1, float> quant16_scale = { 1, { 0.00390625, } };
const TfLiteAffineQuantization quant16 = { (TfLiteFloatArray*)&quant16_scale, (TfLiteIntArray*)&g0::quant11_zero, 0 };
const TfLiteFullyConnectedParams opdata0 = { kTfLiteActRelu, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs0 = { 3, { 0,10,9 } };
const TfArray<1, int> outputs0 = { 1, { 11 } };
const TfLiteFullyConnectedParams opdata1 = { kTfLiteActRelu, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs1 = { 3, { 11,8,7 } };
const TfArray<1, int> outputs1 = { 1, { 12 } };
const TfLiteFullyConnectedParams opdata2 = { kTfLiteActRelu, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs2 = { 3, { 12,6,5 } };
const TfArray<1, int> outputs2 = { 1, { 13 } };
const TfLiteFullyConnectedParams opdata3 = { kTfLiteActRelu, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs3 = { 3, { 13,4,3 } };
const TfArray<1, int> outputs3 = { 1, { 14 } };
const TfLiteFullyConnectedParams opdata4 = { kTfLiteActNone, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs4 = { 3, { 14,2,1 } };
const TfArray<1, int> outputs4 = { 1, { 15 } };
const TfLiteSoftmaxParams opdata5 = { 1 };
const TfArray<1, int> inputs5 = { 1, { 15 } };
const TfArray<1, int> outputs5 = { 1, { 16 } };
};

TensorInfo_t tensorData[] = {
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension0, 26, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant0))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data1, (TfLiteIntArray*)&g0::tensor_dimension1, 16, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant1))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data2, (TfLiteIntArray*)&g0::tensor_dimension2, 64, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant2))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data3, (TfLiteIntArray*)&g0::tensor_dimension3, 64, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant3))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data4, (TfLiteIntArray*)&g0::tensor_dimension4, 256, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant4))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data5, (TfLiteIntArray*)&g0::tensor_dimension3, 64, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant5))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data6, (TfLiteIntArray*)&g0::tensor_dimension6, 512, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant6))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data7, (TfLiteIntArray*)&g0::tensor_dimension7, 128, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant7))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data8, (TfLiteIntArray*)&g0::tensor_dimension8, 1024, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant8))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data9, (TfLiteIntArray*)&g0::tensor_dimension7, 128, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant9))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data10, (TfLiteIntArray*)&g0::tensor_dimension10, 832, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant10))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 32), (TfLiteIntArray*)&g0::tensor_dimension11, 32, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant11))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension11, 32, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant12))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 32), (TfLiteIntArray*)&g0::tensor_dimension13, 16, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant13))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension13, 16, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant14))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 16), (TfLiteIntArray*)&g0::tensor_dimension15, 4, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant15))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension15, 4, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant16))}, },
};

#ifndef TF_LITE_STATIC_MEMORY
TfLiteNode tflNodes[6] = {
{ (TfLiteIntArray*)&g0::inputs0, (TfLiteIntArray*)&g0::outputs0, (TfLiteIntArray*)&g0::inputs0, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata0)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs1, (TfLiteIntArray*)&g0::outputs1, (TfLiteIntArray*)&g0::inputs1, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata1)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs2, (TfLiteIntArray*)&g0::outputs2, (TfLiteIntArray*)&g0::inputs2, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata2)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs3, (TfLiteIntArray*)&g0::outputs3, (TfLiteIntArray*)&g0::inputs3, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata3)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs4, (TfLiteIntArray*)&g0::outputs4, (TfLiteIntArray*)&g0::inputs4, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata4)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs5, (TfLiteIntArray*)&g0::outputs5, (TfLiteIntArray*)&g0::inputs5, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata5)), nullptr, 0, },
};
#else
TfLiteNode tflNodes[6] = {
{ (TfLiteIntArray*)&g0::inputs0, (TfLiteIntArray*)&g0::outputs0, (TfLiteIntArray*)&g0::inputs0, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata0)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs1, (TfLiteIntArray*)&g0::outputs1, (TfLiteIntArray*)&g0::inputs1, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata1)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs2, (TfLiteIntArray*)&g0::outputs2, (TfLiteIntArray*)&g0::inputs2, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata2)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs3, (TfLiteIntArray*)&g0::outputs3, (TfLiteIntArray*)&g0::inputs3, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata3)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs4, (TfLiteIntArray*)&g0::outputs4, (TfLiteIntArray*)&g0::inputs4, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata4)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs5, (TfLiteIntArray*)&g0::outputs5, (TfLiteIntArray*)&g0::inputs5, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata5)), nullptr, 0, },
};
#endif

used_operators_e used_ops[] =
{OP_FULLY_CONNECTED, OP_FULLY_CONNECTED, OP_FULLY_CONNECTED, OP_FULLY_CONNECTED, OP_FULLY_CONNECTED, OP_SOFTMAX, };


// Indices into tflTensors and tflNodes for subgraphs
const size_t tflTensors_subgraph_index[] = {0, 17, };
const size_t tflNodes_subgraph_index[] = {0, 6, };

// Input/output tensors
static const int in_tensor_indices[] = {
  0, 
};

static const int out_tensor_indices[] = {
  16, 
};


size_t current_subgraph_index = 0;

static void init_tflite_tensor(size_t i, TfLiteTensor *tensor) {
  tensor->type = tensorData[i].type;
  tensor->is_variable = false;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  tensor->allocation_type = tensorData[i].allocation_type;
#else
  tensor->allocation_type = (tensor_arena <= tensorData[i].data && tensorData[i].data < tensor_arena + kTensorArenaSize) ? kTfLiteArenaRw : kTfLiteMmapRo;
#endif
  tensor->bytes = tensorData[i].bytes;
  tensor->dims = tensorData[i].dims;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  if(tensor->allocation_type == kTfLiteArenaRw){
    uint8_t* start = (uint8_t*) ((uintptr_t)tensorData[i].data + (uintptr_t) tensor_arena);

    tensor->data.data =  start;
  }
  else {
      tensor->data.data = tensorData[i].data;
  }
#else
  tensor->data.data = tensorData[i].data;
#endif // EI_CLASSIFIER_ALLOCATION_HEAP
  tensor->quantization = tensorData[i].quantization;
  if (tensor->quantization.type == kTfLiteAffineQuantization) {
    TfLiteAffineQuantization const* quant = ((TfLiteAffineQuantization const*)(tensorData[i].quantization.params));
    tensor->params.scale = quant->scale->data[0];
    tensor->params.zero_point = quant->zero_point->data[0];
  }

}

static void init_tflite_eval_tensor(int i, TfLiteEvalTensor *tensor) {

  tensor->type = tensorData[i].type;

  tensor->dims = tensorData[i].dims;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  auto allocation_type = tensorData[i].allocation_type;
  if(allocation_type == kTfLiteArenaRw) {
    uint8_t* start = (uint8_t*) ((uintptr_t)tensorData[i].data + (uintptr_t) tensor_arena);

    tensor->data.data =  start;
  }
  else {
    tensor->data.data = tensorData[i].data;
  }
#else
  tensor->data.data = tensorData[i].data;
#endif // EI_CLASSIFIER_ALLOCATION_HEAP
}

static void* overflow_buffers[EI_MAX_OVERFLOW_BUFFER_COUNT];
static size_t overflow_buffers_ix = 0;
static void * AllocatePersistentBufferImpl(struct TfLiteContext* ctx,
                                       size_t bytes) {
  void *ptr;
  uint32_t align_bytes = (bytes % 16) ? 16 - (bytes % 16) : 0;

  if (current_location - (bytes + align_bytes) < tensor_boundary) {
    if (overflow_buffers_ix > EI_MAX_OVERFLOW_BUFFER_COUNT - 1) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d, does not fit in tensor arena and reached EI_MAX_OVERFLOW_BUFFER_COUNT\n",
        (int)bytes);
      return NULL;
    }

    // OK, this will look super weird, but.... we have CMSIS-NN buffers which
    // we cannot calculate beforehand easily.
    ptr = ei_calloc(bytes, 1);
    if (ptr == NULL) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d\n", (int)bytes);
      return NULL;
    }
    overflow_buffers[overflow_buffers_ix++] = ptr;
    return ptr;
  }

  current_location -= bytes;

  // align to the left aligned boundary of 16 bytes
  current_location -= 15; // for alignment
  current_location += 16 - ((uintptr_t)(current_location) & 15);

  ptr = current_location;
  memset(ptr, 0, bytes);

  return ptr;
}

typedef struct {
  size_t bytes;
  void *ptr;
} scratch_buffer_t;

static scratch_buffer_t scratch_buffers[EI_MAX_SCRATCH_BUFFER_COUNT];
static size_t scratch_buffers_ix = 0;

static TfLiteStatus RequestScratchBufferInArenaImpl(struct TfLiteContext* ctx, size_t bytes,
                                                int* buffer_idx) {
  if (scratch_buffers_ix > EI_MAX_SCRATCH_BUFFER_COUNT - 1) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d, reached EI_MAX_SCRATCH_BUFFER_COUNT\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffer_t b;
  b.bytes = bytes;

  b.ptr = AllocatePersistentBufferImpl(ctx, b.bytes);
  if (!b.ptr) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffers[scratch_buffers_ix] = b;
  *buffer_idx = scratch_buffers_ix;

  scratch_buffers_ix++;

  return kTfLiteOk;
}

static void* GetScratchBufferImpl(struct TfLiteContext* ctx, int buffer_idx) {
  if (buffer_idx > (int)scratch_buffers_ix) {
    return NULL;
  }
  return scratch_buffers[buffer_idx].ptr;
}

static const uint16_t TENSOR_IX_UNUSED = 0x7FFF;

static void ResetTensors() {
  for (size_t ix = 0; ix < MAX_TFL_TENSOR_COUNT; ix++) {
    tflTensors[ix].index = TENSOR_IX_UNUSED;
  }
  for (size_t ix = 0; ix < MAX_TFL_EVAL_COUNT; ix++) {
    tflEvalTensors[ix].index = TENSOR_IX_UNUSED;
  }
}

static TfLiteTensor* GetTensorImpl(const struct TfLiteContext* context,
                               int tensor_idx) {

  tensor_idx = tflTensors_subgraph_index[current_subgraph_index] + tensor_idx;

  for (size_t ix = 0; ix < MAX_TFL_TENSOR_COUNT; ix++) {
    // already used? OK!
    if (tflTensors[ix].index == tensor_idx) {
      return &tflTensors[ix].tensor;
    }
    // passed all the ones we've used, so end of the list?
    if (tflTensors[ix].index == TENSOR_IX_UNUSED) {
      // init the tensor
      init_tflite_tensor(tensor_idx, &tflTensors[ix].tensor);
      tflTensors[ix].index = tensor_idx;
      return &tflTensors[ix].tensor;
    }
  }

  ei_printf("ERR: GetTensor called beyond MAX_TFL_TENSOR_COUNT (%d)\n", MAX_TFL_TENSOR_COUNT);
  return nullptr;
}

static TfLiteEvalTensor* GetEvalTensorImpl(const struct TfLiteContext* context,
                                       int tensor_idx) {

  tensor_idx = tflTensors_subgraph_index[current_subgraph_index] + tensor_idx;

  for (size_t ix = 0; ix < MAX_TFL_EVAL_COUNT; ix++) {
    // already used? OK!
    if (tflEvalTensors[ix].index == tensor_idx) {
      return &tflEvalTensors[ix].tensor;
    }
    // passed all the ones we've used, so end of the list?
    if (tflEvalTensors[ix].index == TENSOR_IX_UNUSED) {
      // init the tensor
      init_tflite_eval_tensor(tensor_idx, &tflEvalTensors[ix].tensor);
      tflEvalTensors[ix].index = tensor_idx;
      return &tflEvalTensors[ix].tensor;
    }
  }

  ei_printf("ERR: GetTensor called beyond MAX_TFL_EVAL_COUNT (%d)\n", (int)MAX_TFL_EVAL_COUNT);
  return nullptr;
}

class EonMicroContext : public MicroContext {
 public:
 
  EonMicroContext(): MicroContext(nullptr, nullptr, nullptr) { }

  void* AllocatePersistentBuffer(size_t bytes) {
    return AllocatePersistentBufferImpl(nullptr, bytes);
  }

  TfLiteStatus RequestScratchBufferInArena(size_t bytes,
                                           int* buffer_index) {
  return RequestScratchBufferInArenaImpl(nullptr, bytes, buffer_index);
  }

  void* GetScratchBuffer(int buffer_index) {
    return GetScratchBufferImpl(nullptr, buffer_index);
  }
 
  TfLiteTensor* AllocateTempTfLiteTensor(int tensor_index) {
    return GetTensorImpl(nullptr, tensor_index);
  }

  void DeallocateTempTfLiteTensor(TfLiteTensor* tensor) {
    return;
  }

  bool IsAllTempTfLiteTensorDeallocated() {
    return true;
  }

  TfLiteEvalTensor* GetEvalTensor(int tensor_index) {
    return GetEvalTensorImpl(nullptr, tensor_index);
  }

};


} // namespace

TfLiteStatus tflite_learn_1022943_5_init( void*(*alloc_fnc)(size_t,size_t) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  tensor_arena = (uint8_t*) alloc_fnc(16, kTensorArenaSize);
  if (!tensor_arena) {
    ei_printf("ERR: failed to allocate tensor arena\n");
    return kTfLiteError;
  }
#else
  memset(tensor_arena, 0, kTensorArenaSize);
#endif
  tensor_boundary = tensor_arena;
  current_location = tensor_arena + kTensorArenaSize;

  EonMicroContext micro_context_;
  
  // Set microcontext as the context ptr
  ctx.impl_ = static_cast<void*>(&micro_context_);
  // Setup tflitecontext functions
  ctx.AllocatePersistentBuffer = &AllocatePersistentBufferImpl;
  ctx.RequestScratchBufferInArena = &RequestScratchBufferInArenaImpl;
  ctx.GetScratchBuffer = &GetScratchBufferImpl;
  ctx.GetTensor = &GetTensorImpl;
  ctx.GetEvalTensor = &GetEvalTensorImpl;
  ctx.ReportError = &MicroContextReportOpError;

  ctx.tensors_size = 17;
  for (size_t i = 0; i < 17; ++i) {
    TfLiteTensor tensor;
    init_tflite_tensor(i, &tensor);
    if (tensor.allocation_type == kTfLiteArenaRw) {
      auto data_end_ptr = (uint8_t*)tensor.data.data + tensorData[i].bytes;
      if (data_end_ptr > tensor_boundary) {
        tensor_boundary = data_end_ptr;
      }
    }
  }

  if (tensor_boundary > current_location /* end of arena size */) {
    ei_printf("ERR: tensor arena is too small, does not fit model - even without scratch buffers\n");
    return kTfLiteError;
  }

  registrations[OP_FULLY_CONNECTED] = Register_FULLY_CONNECTED();
  registrations[OP_SOFTMAX] = Register_SOFTMAX();

  for (size_t g = 0; g < 1; ++g) {
    current_subgraph_index = g;
    for(size_t i = tflNodes_subgraph_index[g]; i < tflNodes_subgraph_index[g+1]; ++i) {
      if (registrations[used_ops[i]].init) {
        tflNodes[i].user_data = registrations[used_ops[i]].init(&ctx, (const char*)tflNodes[i].builtin_data, 0);
      }
    }
  }
  current_subgraph_index = 0;

  for(size_t g = 0; g < 1; ++g) {
    current_subgraph_index = g;
    for(size_t i = tflNodes_subgraph_index[g]; i < tflNodes_subgraph_index[g+1]; ++i) {
      if (registrations[used_ops[i]].prepare) {
        ResetTensors();
        TfLiteStatus status = registrations[used_ops[i]].prepare(&ctx, &tflNodes[i]);
        if (status != kTfLiteOk) {
          return status;
        }
      }
    }
  }
  current_subgraph_index = 0;

  return kTfLiteOk;
}

TfLiteStatus tflite_learn_1022943_5_input(int index, TfLiteTensor *tensor) {
  init_tflite_tensor(in_tensor_indices[index], tensor);
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_1022943_5_output(int index, TfLiteTensor *tensor) {
  init_tflite_tensor(out_tensor_indices[index], tensor);
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_1022943_5_invoke() {
  for (size_t i = 0; i < 6; ++i) {
    ResetTensors();

    TfLiteStatus status = registrations[used_ops[i]].invoke(&ctx, &tflNodes[i]);

#if EI_CLASSIFIER_PRINT_STATE
    ei_printf("layer %lu\n", i);
    ei_printf("    inputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].inputs->size; ix++) {
      auto d = tensorData[tflNodes[i].inputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");

    ei_printf("    outputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].outputs->size; ix++) {
      auto d = tensorData[tflNodes[i].outputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");
#endif // EI_CLASSIFIER_PRINT_STATE

    if (status != kTfLiteOk) {
      return status;
    }
  }
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_1022943_5_reset( void (*free_fnc)(void* ptr) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  free_fnc(tensor_arena);
#endif

  // scratch buffers are allocated within the arena, so just reset the counter so memory can be reused
  scratch_buffers_ix = 0;

  // overflow buffers are on the heap, so free them first
  for (size_t ix = 0; ix < overflow_buffers_ix; ix++) {
    ei_free(overflow_buffers[ix]);
  }
  overflow_buffers_ix = 0;
  return kTfLiteOk;
}
