/*
 * Copyright (c) 2026 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://edgeimpulse.com/legal/terms-of-service) or Enterprise Terms of
 * Service (https://edgeimpulse.com/legal/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */

#ifndef _EI_CLASSIFIER_MODEL_VARIABLES_H_
#define _EI_CLASSIFIER_MODEL_VARIABLES_H_

/**
 * @file
 *  Auto-generated complete impulse definitions. The ei_impulse_handle_t should
 *  be passed to ei_run_classifier() function to use this specific impulse.
 *  This file should only be included in ei_run_classifier.h file.
 */

#include <stdint.h>
#include "model_metadata.h"
#include "tflite-model/tflite_learn_1022943_5_compiled.h"
#include "edge-impulse-sdk/classifier/ei_model_types.h"
#include "edge-impulse-sdk/classifier/inferencing_engines/engines.h"
#include "edge-impulse-sdk/classifier/postprocessing/ei_postprocessing_common.h"

const char* ei_classifier_inferencing_categories_1022943_1[] = { "extension", "fist", "flexion", "rest" };

EI_CLASSIFIER_DSP_AXES_INDEX_TYPE ei_dsp_config_1022943_4_axes[] = { 0, 1 };
const uint32_t ei_dsp_config_1022943_4_axes_size = 2;
ei_dsp_config_spectral_analysis_t ei_dsp_config_1022943_4 = {
    4, // uint32_t blockId
    4, // int implementationVersion
    2, // int length of axes
    1.0f, // float scale-axes
    1, // int input-decimation-ratio
    "none", // select filter-type
    3.0f, // float filter-cutoff
    6, // int filter-order
    "FFT", // select analysis-type
    16, // int fft-length
    3, // int spectral-peaks-count
    0.1f, // float spectral-peaks-threshold
    "0.1, 0.5, 1.0, 2.0, 5.0", // string spectral-power-edges
    true, // boolean do-log
    true, // boolean do-fft-overlap
    1, // int wavelet-level
    "db4", // select wavelet
    false // boolean extra-low-freq
};

const float ei_dn_standard_scaler_mean_1022943_4[26] = { 4.9620063920815785, -0.3285320178295175, 0.41468962477811144, 2.13479019900163, 3.17061154594024, 1.6117634713649749, 1.3123204797506332, 1.1132548908392588, 0.9450363963842392, 0.9206242844462394, 0.9089730679988861, 0.9060498277346293, 1.0466443598270416, 3.9833861897389093, 0.29038011595839636, 0.5527176988466332, 2.261771395802498, 3.5003641813993456, 1.6643608103195826, 1.338305579125881, 1.1407932375868162, 0.9553311263521512, 0.9097533792257309, 0.8285873765746753, 0.8195379614830017, 0.9817149336139361 };
const float ei_dn_standard_scaler_scale_1022943_4[26] = { 0.2623754981054789, 1.3332335637924966, 1.025920293949772, 1.6571249739083365, 0.6036724229134932, 1.4766645019815665, 1.9445563165839723, 2.6108378202211586, 3.296029944726602, 3.938246479105233, 4.523258978009752, 4.377053447535624, 4.671754063884014, 0.37439109192467657, 2.361887648529747, 0.9652960378610678, 2.5193386613955435, 0.8891889169501848, 1.3939872449604602, 1.9757861154534966, 2.423543817803377, 3.78987619746214, 3.8970905475587467, 5.154259928337716, 6.010012548747844, 5.000489699006217 };
const float ei_dn_standard_scaler_var_1022943_4[26] = { 14.52624778088202, 0.5625841899995105, 0.9501075264610525, 0.36415768129168735, 2.7440835253828353, 0.45860240748939873, 0.26445936410422255, 0.14670341027964662, 0.09204870918705207, 0.0644754249469736, 0.04887616162251043, 0.05219588919421705, 0.04581841440560712, 7.134260882731599, 0.17925923138044858, 1.0731957714259295, 0.15755307990024423, 1.2647710555901879, 0.5146149516396488, 0.2561652065392099, 0.17025436201594368, 0.06962255444864647, 0.06584442459983043, 0.037641538666032134, 0.027685300540614712, 0.03999216596681479 };
ei_data_normalization_standard_scaler_config_t ei_data_normalization_standard_scaler_config_1022943_4 = {
    .mean_data = (float *)ei_dn_standard_scaler_mean_1022943_4,
    .mean_data_len = 26,
    .scale_data = (float *)ei_dn_standard_scaler_scale_1022943_4,
    .scale_data_len = 26,
    .var_data = (float *)ei_dn_standard_scaler_var_1022943_4,
    .var_data_len = 26
};
ei_data_normalization_t ei_data_normalization_config_1022943_4 = {
    (void *) &ei_data_normalization_standard_scaler_config_1022943_4, // config
    DATA_NORMALIZATION_METHOD_STANDARD_SCALER, // method
    nullptr, // context
    nullptr, // init func
    nullptr, // deinit func
    &data_normalization_standard_scaler // exec func
};

const uint8_t ei_dsp_blocks_1022943_1_size = 1;
ei_model_dsp_t ei_dsp_blocks_1022943_1[ei_dsp_blocks_1022943_1_size] = {
    { // DSP block 4
        4,
        26, // output size
        &extract_spectral_analysis_features, // DSP function pointer
        (void*)&ei_dsp_config_1022943_4, // pointer to config struct
        ei_dsp_config_1022943_4_axes, // array of offsets into the input stream, one for each axis
        ei_dsp_config_1022943_4_axes_size, // number of axes
        1, // version
        nullptr, // factory function
        &ei_data_normalization_config_1022943_4, // data normalization config
    }
};
const ei_config_tflite_eon_graph_t ei_config_graph_1022943_5 = {
    .implementation_version = 1,
    .model_init = &tflite_learn_1022943_5_init,
    .model_invoke = &tflite_learn_1022943_5_invoke,
    .model_reset = &tflite_learn_1022943_5_reset,
    .model_input = &tflite_learn_1022943_5_input,
    .model_output = &tflite_learn_1022943_5_output,
};

const uint8_t ei_output_tensors_indices_1022943_5[1] = { 0 };
const uint8_t ei_output_tensors_size_1022943_5 = 1;
ei_learning_block_config_tflite_graph_t ei_learning_block_config_1022943_5 = {
    .implementation_version = 1,
    .block_id = 5,
    .output_tensors_indices = ei_output_tensors_indices_1022943_5,
    .output_tensors_size = ei_output_tensors_size_1022943_5,
    .quantized = 1,
    .compiled = 1,
    .graph_config = (void*)&ei_config_graph_1022943_5,
    .dequantize_output = 0,
};

const uint8_t ei_learning_blocks_1022943_1_size = 1;
const uint32_t ei_learning_block_1022943_5_inputs[1] = { 4 };
const uint8_t ei_learning_block_1022943_5_inputs_size = 1;
const ei_learning_block_t ei_learning_blocks_1022943_1[ei_learning_blocks_1022943_1_size] = {
    {
        5,
        &run_nn_inference,
        (void*)&ei_learning_block_config_1022943_5,
        EI_CLASSIFIER_IMAGE_SCALING_NONE,
        ei_learning_block_1022943_5_inputs,
        ei_learning_block_1022943_5_inputs_size,
    },
};

ei_fill_result_classification_i8_config_t ei_fill_result_classification_i8_config_1022943_5 = {
    .zero_point = -128,
    .scale = 0.00390625
};

const size_t ei_postprocessing_blocks_1022943_1_size = 1;
const ei_postprocessing_block_t ei_postprocessing_blocks_1022943_1[ei_postprocessing_blocks_1022943_1_size] = {
    {
        .block_id = 5,
        .type = EI_CLASSIFIER_MODE_CLASSIFICATION,
        .init_fn = NULL,
        .deinit_fn = NULL,
        .postprocess_fn = &process_classification_i8,
        .display_fn = NULL,
        .config = (void*)&ei_fill_result_classification_i8_config_1022943_5,
        .input_block_id = 5
    },
};

const uint8_t freeform_outputs_1022943_1_size = 0;

uint32_t *freeform_outputs_1022943_1 = nullptr;

const ei_impulse_t impulse_1022943_1 = {
    .project_id = 1022943,
    .project_owner = "amirfrf",
    .project_name = "pre-demo project emg sensors",
    .impulse_id = 1,
    .impulse_name = "Impulse #1",
    .deploy_version = 3,

    .nn_input_frame_size = 26,
    .raw_sample_count = 499,
    .raw_samples_per_frame = 2,
    .dsp_input_frame_size = 499 * 2,
    .input_width = 0,
    .input_height = 0,
    .input_frames = 0,
    .interval_ms = 2.004008016032064,
    .frequency = 499,

    .dsp_blocks_size = ei_dsp_blocks_1022943_1_size,
    .dsp_blocks = ei_dsp_blocks_1022943_1,

    .learning_blocks_size = ei_learning_blocks_1022943_1_size,
    .learning_blocks = ei_learning_blocks_1022943_1,

    .postprocessing_blocks_size = ei_postprocessing_blocks_1022943_1_size,
    .postprocessing_blocks = ei_postprocessing_blocks_1022943_1,

    .output_tensors_size = 1,

    .inferencing_engine = EI_CLASSIFIER_TFLITE,

    .sensor = EI_CLASSIFIER_SENSOR_FUSION,
    .fusion_string = "a0 + a1",
    .slice_size = (499/4),
    .slices_per_model_window = 4,

    .has_anomaly = EI_ANOMALY_TYPE_UNKNOWN,
    .label_count = 4,
    .categories = ei_classifier_inferencing_categories_1022943_1,
    .results_type = EI_CLASSIFIER_TYPE_CLASSIFICATION,
    .freeform_outputs_size = freeform_outputs_1022943_1_size,
    .freeform_outputs = freeform_outputs_1022943_1
};

ei_impulse_handle_t impulse_handle_1022943_1 = ei_impulse_handle_t( &impulse_1022943_1 );

ei_impulse_handle_t& ei_default_impulse = impulse_handle_1022943_1;
constexpr auto& ei_classifier_inferencing_categories = ei_classifier_inferencing_categories_1022943_1;
const auto ei_dsp_blocks_size = ei_dsp_blocks_1022943_1_size;
ei_model_dsp_t *ei_dsp_blocks = ei_dsp_blocks_1022943_1;
#endif // _EI_CLASSIFIER_MODEL_VARIABLES_H_
