// Enable/disable debug output via USB
#define DEBUG 1

#include <cstdio>
#include <cstring>
#ifdef DEBUG
#define DBG_PRINT(fmt, ...) printf(fmt, ##__VA_ARGS__)
#else
#define DBG_PRINT(fmt, ...)
#endif
// debug only printf
#include "ble/att_db.h"
#include "ble/att_server.h"
#include "btstack.h"
#include "gap.h"
#include "pico/btstack_cyw43.h"
#include "pico/cyw43_arch.h"
#include "pico/stdlib.h"

// Generated by compile_gatt.py from pico_hand_ble.gatt to be able to ble why is
#include "pico_hand_ble.h"

#include "hand.hpp"

// attribute handles again, why is it so cursed?
#define HANDLE_CMD_VALUE                                                       \
  ATT_CHARACTERISTIC_c3feed71_b50c_400a_836c_c8981beb0b1c_01_VALUE_HANDLE
#define HANDLE_STATE_VALUE                                                     \
  ATT_CHARACTERISTIC_c3feed72_b50c_400a_836c_c8981beb0b1c_01_VALUE_HANDLE
#define HANDLE_STATE_CCC                                                       \
  ATT_CHARACTERISTIC_c3feed72_b50c_400a_836c_c8981beb0b1c_01_CLIENT_CONFIGURATION_HANDLE

static Hand *g_hand = nullptr;
static hci_con_handle_t g_con_handle = HCI_CON_HANDLE_INVALID;
static char g_last_gesture[16] = "relax";

static btstack_packet_callback_registration_t hci_cb_reg;

static void dispatch_gesture(const char *cmd) {
  DBG_PRINT("pico: Received gesture command: %s\n", cmd);
  if (!g_hand) {
    DBG_PRINT("pico: ERROR: Hand pointer is null!\n");
    // like itll ever happen.... but still dont hurt to check
    return;
  }

  if (strcmp(cmd, "open") == 0) {
    g_hand->OpenPalm();
    DBG_PRINT("pico: → Moving to OPEN\n");
  } else if (strcmp(cmd, "fist") == 0) {
    g_hand->Fist();
    DBG_PRINT("pico: → Moving to FIST\n");
  } else if (strcmp(cmd, "pinch") == 0) {
    g_hand->Pinch();
    DBG_PRINT("pico: → Moving to PINCH\n");
  } else if (strcmp(cmd, "point") == 0) {
    g_hand->Point();
    DBG_PRINT("pico: → Moving to POINT\n");
  } else if (strcmp(cmd, "like") == 0) {
    g_hand->Like();
    DBG_PRINT("pico: → Moving to LIKE\n");
  } else if (strcmp(cmd, "relax") == 0) {
    g_hand->Relax();
    DBG_PRINT("pico: → Moving to RELAX\n");
  } else
    DBG_PRINT("pico: ERROR: Unknown gesture: %s\n", cmd);
}

static int att_write_callback(hci_con_handle_t con_handle, uint16_t att_handle,
                              uint16_t transaction_mode, uint16_t offset,
                              uint8_t *buffer, uint16_t buffer_size) {
  (void)con_handle;
  (void)transaction_mode;
  (void)offset;

  if (att_handle == HANDLE_CMD_VALUE) {
    DBG_PRINT("pico: ATT write: handle=0x%04x, size=%u\n", att_handle,
              buffer_size);
    uint16_t len = buffer_size < (uint16_t)(sizeof(g_last_gesture) - 1)
                       ? buffer_size
                       : (uint16_t)(sizeof(g_last_gesture) - 1);
    memcpy(g_last_gesture, buffer, len);
    g_last_gesture[len] = '\0';
    dispatch_gesture(g_last_gesture);
  }
  return 0;
}

// att write, again kinda weirdt things but its what bttstack makes us do sooo
static uint16_t att_read_callback(hci_con_handle_t con_handle,
                                  uint16_t att_handle, uint16_t offset,
                                  uint8_t *buffer, uint16_t buffer_size) {
  (void)con_handle;

  if (att_handle == HANDLE_STATE_VALUE) {
    return att_read_callback_handle_blob((const uint8_t *)g_last_gesture,
                                         (uint16_t)strlen(g_last_gesture),
                                         offset, buffer, buffer_size);
  }
  return 0;
}
// now read instead!
static void hci_packet_handler(uint8_t packet_type, uint16_t channel,
                               uint8_t *packet, uint16_t size) {
  (void)channel;
  (void)size;
  if (packet_type != HCI_EVENT_PACKET)
    return;

  switch (hci_event_packet_get_type(packet)) {

  case BTSTACK_EVENT_STATE:
    if (btstack_event_state_get_state(packet) == HCI_STATE_WORKING) {
      DBG_PRINT("pico: BLE up — advertising as PicoHand\n");

      uint16_t adv_min = 0x0030;
      uint16_t adv_max = 0x0060;
      bd_addr_t null_addr = {};

      // 0x00 = ADV_IND (connectable undirected)
      gap_advertisements_set_params(adv_min, adv_max, 0x00, 0, null_addr, 0x07,
                                    0x00);

      static const uint8_t adv_data[] = {
          0x02,
          BLUETOOTH_DATA_TYPE_FLAGS,
          0x06,
          0x11,
          0x06,
          0x1c,
          0x0b,
          0xeb,
          0x1b,
          0x98,
          0xc8,
          0x6c,
          0x83,
          0x0a,
          0x40,
          0x0c,
          0xb5,
          0x70,
          0xed,
          0xfe,
          0xc3,
          0x09,
          BLUETOOTH_DATA_TYPE_COMPLETE_LOCAL_NAME,
          'P',
          'i',
          'c',
          'o',
          'H',
          'a',
          'n',
          'd'};
      gap_advertisements_set_data(sizeof(adv_data), (uint8_t *)adv_data);
      gap_advertisements_enable(1);
    }
    break;

  case HCI_EVENT_LE_META:
    if (hci_event_le_meta_get_subevent_code(packet) ==
        HCI_SUBEVENT_LE_CONNECTION_COMPLETE) {
      g_con_handle =
          hci_subevent_le_connection_complete_get_connection_handle(packet);
      DBG_PRINT("pico: Nano connected, handle=0x%04x\n", g_con_handle);
    }
    break;

  case HCI_EVENT_DISCONNECTION_COMPLETE:
    DBG_PRINT("pico: Disconnected — restarting advertising\n");
    g_con_handle = HCI_CON_HANDLE_INVALID;
    gap_advertisements_enable(1);
    break;

  default:
    break;
  }
}
// yeah, uh-huh. PLS don't touch ANYTHING here.

int main() {
  stdio_init_all();
  sleep_ms(3000); // is this enough pls

  DBG_PRINT("pico: Pico W is ready to fire up\n");
  printf("hi!???");

  if (cyw43_arch_init()) {
    DBG_PRINT("pico: ERROR: cyw43_arch_init failed!, sorry no BLE\n");
    return 1;
  }

  Hand hand;
  g_hand = &hand;
  DBG_PRINT("pico: Servos initialized\n");
  hand.Fist();
  printf("fist trial \n \n");
  sleep_ms(299);
  hand.OpenPalm();
  printf("openpalm trial \n \n");
  l2cap_init();
  sm_init();
  sm_set_io_capabilities(IO_CAPABILITY_NO_INPUT_NO_OUTPUT);

  // profile_data is defined in the pico_hand_ble.h
  att_server_init(profile_data, att_read_callback, att_write_callback);
  att_server_register_packet_handler(hci_packet_handler);

  hci_cb_reg.callback = &hci_packet_handler;
  hci_add_event_handler(&hci_cb_reg);

  hci_power_control(HCI_POWER_ON);

  DBG_PRINT("pico: Entering BTstack run loop, good luck\n");
  btstack_run_loop_execute();

  return 0;
}