[env:nano33ble]
platform = nordicnrf52
board = nano33ble
framework = arduino

lib_deps = 
    arduino-libraries/ArduinoBLE@^1.3.6
    arduino-libraries/Arduino_HTS221@^1.0.0

monitor_speed = 9600
upload_protocol = sam-ba

[env:nano33ble-test]
platform = nordicnrf52
board = nano33ble
framework = arduino
test_framework = unity

lib_deps = 
    arduino-libraries/ArduinoBLE@^1.3.6
    arduino-libraries/Arduino_HTS221@^1.0.0
